
# had to change the buikd system and now it works
[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "timeutils"
version = "0.1.0"
[tool.setuptools.packages.find]
where = ["src"]

